# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'culcul_proj.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(786, 297)
        MainWindow.setStyleSheet("background-color:rgb(47, 54, 64)")
        MainWindow.setProperty("flat", QtGui.QColor(44, 62, 80))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.multipl_butt = QtWidgets.QPushButton(self.centralwidget)
        self.multipl_butt.setGeometry(QtCore.QRect(680, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multipl_butt.setFont(font)
        self.multipl_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.multipl_butt.setObjectName("multipl_butt")
        self.plus_butt = QtWidgets.QPushButton(self.centralwidget)
        self.plus_butt.setGeometry(QtCore.QRect(680, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plus_butt.setFont(font)
        self.plus_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.plus_butt.setObjectName("plus_butt")
        self.divise_butt = QtWidgets.QPushButton(self.centralwidget)
        self.divise_butt.setGeometry(QtCore.QRect(680, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.divise_butt.setFont(font)
        self.divise_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.divise_butt.setObjectName("divise_butt")
        self.butt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_3.setGeometry(QtCore.QRect(570, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_3.setFont(font)
        self.butt_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_3.setObjectName("butt_3")
        self.minu_butt = QtWidgets.QPushButton(self.centralwidget)
        self.minu_butt.setGeometry(QtCore.QRect(680, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minu_butt.setFont(font)
        self.minu_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.minu_butt.setObjectName("minu_butt")
        self.equal_butt = QtWidgets.QPushButton(self.centralwidget)
        self.equal_butt.setGeometry(QtCore.QRect(570, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.equal_butt.setFont(font)
        self.equal_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.equal_butt.setObjectName("equal_butt")
        self.butt_6 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_6.setGeometry(QtCore.QRect(570, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_6.setFont(font)
        self.butt_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_6.setObjectName("butt_6")
        self.clear_butt = QtWidgets.QPushButton(self.centralwidget)
        self.clear_butt.setGeometry(QtCore.QRect(680, 110, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clear_butt.setFont(font)
        self.clear_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.clear_butt.setObjectName("clear_butt")
        self.butt_9 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_9.setGeometry(QtCore.QRect(570, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_9.setFont(font)
        self.butt_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_9.setObjectName("butt_9")
        self.percentage_butt = QtWidgets.QPushButton(self.centralwidget)
        self.percentage_butt.setGeometry(QtCore.QRect(570, 110, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.percentage_butt.setFont(font)
        self.percentage_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.percentage_butt.setObjectName("percentage_butt")
        self.paren_1 = QtWidgets.QPushButton(self.centralwidget)
        self.paren_1.setGeometry(QtCore.QRect(350, 110, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paren_1.setFont(font)
        self.paren_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.paren_1.setObjectName("paren_1")
        self.point_butt = QtWidgets.QPushButton(self.centralwidget)
        self.point_butt.setGeometry(QtCore.QRect(460, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.point_butt.setFont(font)
        self.point_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.point_butt.setObjectName("point_butt")
        self.butt_7 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_7.setGeometry(QtCore.QRect(350, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_7.setFont(font)
        self.butt_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_7.setObjectName("butt_7")
        self.butt_8 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_8.setGeometry(QtCore.QRect(460, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_8.setFont(font)
        self.butt_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_8.setObjectName("butt_8")
        self.butt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_2.setGeometry(QtCore.QRect(460, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_2.setFont(font)
        self.butt_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_2.setObjectName("butt_2")
        self.butt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_4.setGeometry(QtCore.QRect(350, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_4.setFont(font)
        self.butt_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_4.setObjectName("butt_4")
        self.butt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_1.setGeometry(QtCore.QRect(350, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_1.setFont(font)
        self.butt_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_1.setObjectName("butt_1")
        self.paren_2 = QtWidgets.QPushButton(self.centralwidget)
        self.paren_2.setGeometry(QtCore.QRect(460, 110, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paren_2.setFont(font)
        self.paren_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.paren_2.setMouseTracking(False)
        self.paren_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.paren_2.setAutoDefault(False)
        self.paren_2.setObjectName("paren_2")
        self.butt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_5.setGeometry(QtCore.QRect(460, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_5.setFont(font)
        self.butt_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_5.setObjectName("butt_5")
        self.butt_0 = QtWidgets.QPushButton(self.centralwidget)
        self.butt_0.setGeometry(QtCore.QRect(350, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.butt_0.setFont(font)
        self.butt_0.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.butt_0.setObjectName("butt_0")
        self.exp_butt = QtWidgets.QPushButton(self.centralwidget)
        self.exp_butt.setGeometry(QtCore.QRect(130, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exp_butt.setFont(font)
        self.exp_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.exp_butt.setObjectName("exp_butt")
        self.sin_butt = QtWidgets.QPushButton(self.centralwidget)
        self.sin_butt.setGeometry(QtCore.QRect(130, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sin_butt.setFont(font)
        self.sin_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.sin_butt.setObjectName("sin_butt")
        self.ln_butt = QtWidgets.QPushButton(self.centralwidget)
        self.ln_butt.setGeometry(QtCore.QRect(240, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_butt.setFont(font)
        self.ln_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.ln_butt.setObjectName("ln_butt")
        self.racine = QtWidgets.QPushButton(self.centralwidget)
        self.racine.setGeometry(QtCore.QRect(240, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.racine.setFont(font)
        self.racine.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.racine.setObjectName("racine")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setEnabled(True)
        self.pushButton_29.setGeometry(QtCore.QRect(240, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.log_butt = QtWidgets.QPushButton(self.centralwidget)
        self.log_butt.setGeometry(QtCore.QRect(240, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.log_butt.setFont(font)
        self.log_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.log_butt.setObjectName("log_butt")
        self.cos_butt = QtWidgets.QPushButton(self.centralwidget)
        self.cos_butt.setGeometry(QtCore.QRect(130, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cos_butt.setFont(font)
        self.cos_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.cos_butt.setObjectName("cos_butt")
        self.tan_butt = QtWidgets.QPushButton(self.centralwidget)
        self.tan_butt.setGeometry(QtCore.QRect(130, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tan_butt.setFont(font)
        self.tan_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.tan_butt.setObjectName("tan_butt")
        self.factoriel_butt = QtWidgets.QPushButton(self.centralwidget)
        self.factoriel_butt.setGeometry(QtCore.QRect(240, 110, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.factoriel_butt.setFont(font)
        self.factoriel_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.factoriel_butt.setObjectName("factoriel_butt")
        self.exp_butt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.exp_butt_2.setGeometry(QtCore.QRect(20, 200, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exp_butt_2.setFont(font)
        self.exp_butt_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.exp_butt_2.setObjectName("exp_butt_2")
        self.pi_butt = QtWidgets.QPushButton(self.centralwidget)
        self.pi_butt.setGeometry(QtCore.QRect(20, 170, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pi_butt.setFont(font)
        self.pi_butt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.pi_butt.setObjectName("pi_butt")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(20, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(20, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(130, 110, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 110, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(149, 165, 166);\n"
"   \n"
"    \n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.divise_butt.raise_()
        self.clear_butt.raise_()
        self.minu_butt.raise_()
        self.butt_0.raise_()
        self.butt_7.raise_()
        self.factoriel_butt.raise_()
        self.cos_butt.raise_()
        self.percentage_butt.raise_()
        self.pushButton_29.raise_()
        self.exp_butt.raise_()
        self.butt_6.raise_()
        self.paren_2.raise_()
        self.butt_4.raise_()
        self.butt_8.raise_()
        self.butt_5.raise_()
        self.plus_butt.raise_()
        self.log_butt.raise_()
        self.racine.raise_()
        self.butt_2.raise_()
        self.equal_butt.raise_()
        self.pi_butt.raise_()
        self.butt_1.raise_()
        self.sin_butt.raise_()
        self.tan_butt.raise_()
        self.paren_1.raise_()
        self.butt_9.raise_()
        self.pushButton_37.raise_()
        self.multipl_butt.raise_()
        self.pushButton_38.raise_()
        self.butt_3.raise_()
        self.point_butt.raise_()
        self.exp_butt_2.raise_()
        self.ln_butt.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Code_Project_ESI"))
        self.multipl_butt.setText(_translate("MainWindow", "X"))
        self.plus_butt.setText(_translate("MainWindow", "+"))
        self.divise_butt.setText(_translate("MainWindow", "/"))
        self.butt_3.setText(_translate("MainWindow", "3"))
        self.minu_butt.setText(_translate("MainWindow", "-"))
        self.equal_butt.setText(_translate("MainWindow", "="))
        self.butt_6.setText(_translate("MainWindow", "6"))
        self.clear_butt.setText(_translate("MainWindow", "AC"))
        self.butt_9.setText(_translate("MainWindow", "9"))
        self.percentage_butt.setText(_translate("MainWindow", "%"))
        self.paren_1.setText(_translate("MainWindow", "("))
        self.point_butt.setText(_translate("MainWindow", "."))
        self.butt_7.setText(_translate("MainWindow", "7"))
        self.butt_8.setText(_translate("MainWindow", "8"))
        self.butt_2.setText(_translate("MainWindow", "2"))
        self.butt_4.setText(_translate("MainWindow", "4"))
        self.butt_1.setText(_translate("MainWindow", "1"))
        self.paren_2.setText(_translate("MainWindow", ")"))
        self.butt_5.setText(_translate("MainWindow", "5"))
        self.butt_0.setText(_translate("MainWindow", "0"))
        self.exp_butt.setText(_translate("MainWindow", "EXP"))
        self.sin_butt.setText(_translate("MainWindow", "sin"))
        self.ln_butt.setText(_translate("MainWindow", "ln"))
        self.racine.setText(_translate("MainWindow", "racine"))
        self.log_butt.setText(_translate("MainWindow", "log"))
        self.cos_butt.setText(_translate("MainWindow", "cos"))
        self.tan_butt.setText(_translate("MainWindow", "tan"))
        self.factoriel_butt.setText(_translate("MainWindow", "x!"))
        self.exp_butt_2.setText(_translate("MainWindow", "e"))
        self.pi_butt.setText(_translate("MainWindow", "pi"))
        self.pushButton_37.setText(_translate("MainWindow", "inv"))
        self.pushButton_38.setText(_translate("MainWindow", "DELETE"))
        self.radioButton.setText(_translate("MainWindow", "deg"))
        self.radioButton_2.setText(_translate("MainWindow", "rad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
